In [1]:
from sklearn.naive_bayes import MultinomialNB

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data = pd.read_csv('C:/Users/N35457.US/Documents/lazyprogrammer/machine_learning_examples-master/nlp_class/spambase.data').as_matrix()

In [5]:
# Before splitting into training and test sets, shuffle the data
np.random.shuffle(data)

In [6]:
X = data[:,:48]

In [7]:
Y = data[:,-1]

In [8]:
# First 100 rows
Xtrain = X[:-100,]
Ytrain = Y[:-100,]

In [9]:
#Last 100 rows
Xtest =  X[-100:,]
Ytest =  Y[-100:,]

In [10]:
model = MultinomialNB()

In [11]:
model.fit(Xtrain, Ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
Xtest

array([[ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       ..., 
       [ 0.  ,  0.  ,  1.03, ...,  0.  ,  0.  ,  0.  ],
       [ 0.05,  0.07,  0.1 , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ]])

In [13]:
Ytest

array([ 1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,
        1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.])

In [14]:
model_score = model.score(Xtest, Ytest)

In [15]:
print ("Classification rate for NB: ", model.score(Xtest, Ytest) )


Classification rate for NB:  0.86


In [16]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier()
model.fit(Xtrain, Ytrain)
print ("Classification rate for AdaBoost: ", model.score(Xtest, Ytest) )

Classification rate for AdaBoost:  0.92


## Spam Detection Redeux

In [55]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
#from wordcloud import WordCloud

In [56]:
# Load Data
df = pd.read_csv('C:/Users/N35457.US/Documents/lazyprogrammer/machine_learning_examples-master/nlp_class/spam.csv', encoding='ISO-8859-1')

In [57]:
df.head()


v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
v1            5572 non-null object
v2            5572 non-null object
Unnamed: 2    50 non-null object
Unnamed: 3    12 non-null object
Unnamed: 4    6 non-null object
dtypes: object(5)
memory usage: 217.7+ KB


In [59]:
# drop unnecessary columns
df = df.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)

In [60]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [61]:
# rename columns to something better
df.columns = ['labels', 'data']

In [62]:
df.head()

labels                                               data
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [63]:
# create binary labels
df['b_labels'] = df['labels'].map({'ham': 0, 'spam': 1})
Y = df['b_labels'].as_matrix()

In [64]:
Y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [65]:
df.head()

labels                                               data  b_labels
0    ham  Go until jurong point, crazy.. Available only ...         0
1    ham                      Ok lar... Joking wif u oni...         0
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...         1
3    ham  U dun say so early hor... U c already then say...         0
4    ham  Nah I don't think he goes to usf, he lives aro...         0

In [75]:
# try multiple ways of calculating features
tfidf = TfidfVectorizer(decode_error='ignore')
X = tfidf.fit_transform(df['data'])


In [76]:
# split up the data
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size=0.33)

In [77]:
# create the model, train it, print scores
model = MultinomialNB()
model.fit(Xtrain, Ytrain)
print("tfidf train score:", model.score(Xtrain, Ytrain))
print("tfidf test score:", model.score(Xtest, Ytest))


tfidf train score: 0.966246986338
tfidf test score: 0.958129418162


In [78]:
count_vectorizer = CountVectorizer(decode_error='ignore')
X = count_vectorizer.fit_transform(df['data'])


In [79]:
# split up the data
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size=0.33)


In [80]:
# create the model, train it, print scores
model = MultinomialNB()
model.fit(Xtrain, Ytrain)
print("count vectorizer train score:", model.score(Xtrain, Ytrain))
print("count vectorizer test score:", model.score(Xtest, Ytest))


count vectorizer train score: 0.994642378784
count vectorizer test score: 0.981511691136


In [71]:
# visualize the data
def visualize(label):
  words = ''
  for msg in df[df['labels'] == label]['data']:
    msg = msg.lower()
    words += msg + ' '
  #wordcloud = WordCloud(width=600, height=400).generate(words)
  #plt.imshow(wordcloud)
  plt.axis('off')
  plt.show()

#visualize('spam')
#visualize('ham')


In [72]:
# see what we're getting wrong
df['predictions'] = model.predict(X)


In [73]:
# things that should be spam
sneaky_spam = df[(df['predictions'] == 0) & (df['b_labels'] == 1)]['data']
for msg in sneaky_spam:
  print(msg)


FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv
Thanks for your subscription to Ringtone UK your mobile will be charged å£5/month Please confirm by replying YES or NO. If you reply NO you will not be charged
SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV
Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out! 
Did you hear about the new \Divorce Barbie\"? It comes with all of Ken's stuff!"
Your free ringtone is waiting to be collected. Simply text the password \MIX\" to 85069 to verify. Get Usher and Britney. FML
You'll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again
FreeMsg Why haven't you replied to my text? I

In [74]:
# things that should not be spam
not_actually_spam = df[(df['predictions'] == 1) & (df['b_labels'] == 0)]['data']
for msg in not_actually_spam:
  print(msg)


## Sentiment Analysis